### ISSUE TITLE
Strings with quotes not parsed correctly

### ISSUE THREAD

**Issue by Algorithmus** [brofield/simpleini#45]
If I have a property value string like this in the ini file:

`property = "value"`

It's not parsed correctly and the resulting string contains the quotes. My understanding of the ini convention is that `value` and `"value"` should be the same string.

**Comment by Demorome** [comment]
I can vouch that this occurs. According to [Wikipedia](https://en.wikipedia.org/wiki/INI_file#Format), only some implementations support this, not all:

> Some implementations allow values to be quoted, typically using double quotes and/or apostrophes. This allows for explicit declaration of whitespace, and/or for quoting of special characters (equals, semicolon, etc.). The standard Windows function GetPrivateProfileString supports this, and will remove quotation marks that surround the values. 

Due to this, I suppose SimpleINI can get away with not following that convention, though I would prefer if it did.
Then again, I'm not sure if there's a way to escape the `"` character otherwise, so maybe it should be an option?

**Comment by brofield** [comment]
Fixed as an option to not break existing usage. Use SetQuotes() to turn it on. Note that this is simple quote support only. See the test cases in tests/ts-quotes.cpp for examples.
https://github.com/brofield/simpleini/commit/bb1db95c752d9b49a854b3cc5b19cc44e3ef2e49
